/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.myschoolapp.view;

/**
 *
 * @author RFR
 */
public class Frame_Rekap extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Beranda
     */
    public Frame_Rekap() {
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerUtama = new javax.swing.JLayeredPane();
        sideBar = new javax.swing.JLayeredPane();
        btnBeranda = new javax.swing.JLabel();
        btnKeuangan = new javax.swing.JLabel();
        btnSiswa = new javax.swing.JLabel();
        btnPembayaran = new javax.swing.JLabel();
        btnRekap = new javax.swing.JLabel();
        MainPane = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cmbDariBulan = new javax.swing.JComboBox<>();
        cmbDariTahun = new javax.swing.JComboBox<>();
        cmbSampaiBulan = new javax.swing.JComboBox<>();
        cmbSampaiTahun = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnMinimz = new javax.swing.JLabel();
        frameBeranda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        containerUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/Beranda_menu.png"))); // NOI18N

        btnKeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/keuangan_menu.png"))); // NOI18N

        btnSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/siswa_menu.png"))); // NOI18N

        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/pemb_menu.png"))); // NOI18N

        btnRekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/rekap_menu_hover.png"))); // NOI18N
        btnRekap.setText("jLabel5");

        sideBar.setLayer(btnBeranda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sideBar.setLayer(btnKeuangan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sideBar.setLayer(btnSiswa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sideBar.setLayer(btnPembayaran, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sideBar.setLayer(btnRekap, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeuangan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnBeranda)
                .addGap(30, 30, 30)
                .addComponent(btnKeuangan)
                .addGap(30, 30, 30)
                .addComponent(btnSiswa)
                .addGap(30, 30, 30)
                .addComponent(btnPembayaran)
                .addGap(30, 30, 30)
                .addComponent(btnRekap)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        containerUtama.add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 640));

        cmbDariBulan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbDariBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));

        cmbDariTahun.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbDariTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021" }));

        cmbSampaiBulan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbSampaiBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));

        cmbSampaiTahun.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cmbSampaiTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021" }));

        btnProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/btn_proses.png"))); // NOI18N

        jLayeredPane1.setLayer(cmbDariBulan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbDariTahun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbSampaiBulan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cmbSampaiTahun, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnProses, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbDariBulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbDariTahun, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSampaiBulan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSampaiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProses))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(cmbDariBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDariTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(cmbSampaiBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSampaiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnProses)
                .addGap(27, 27, 27))
        );

        MainPane.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        containerUtama.add(MainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 1000, 640));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/exit_default.png"))); // NOI18N
        containerUtama.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, 40));

        btnMinimz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/minimz_default.png"))); // NOI18N
        containerUtama.add(btnMinimz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, 40));

        frameBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/myschoolapp/asset/Frame_Rekap.png"))); // NOI18N
        containerUtama.add(frameBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerUtama)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Rekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Rekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Rekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Rekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Rekap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane MainPane;
    private javax.swing.JLabel btnBeranda;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnKeuangan;
    private javax.swing.JLabel btnMinimz;
    private javax.swing.JLabel btnPembayaran;
    private javax.swing.JLabel btnProses;
    private javax.swing.JLabel btnRekap;
    private javax.swing.JLabel btnSiswa;
    private javax.swing.JComboBox<String> cmbDariBulan;
    private javax.swing.JComboBox<String> cmbDariTahun;
    private javax.swing.JComboBox<String> cmbSampaiBulan;
    private javax.swing.JComboBox<String> cmbSampaiTahun;
    private javax.swing.JLayeredPane containerUtama;
    private javax.swing.JLabel frameBeranda;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane sideBar;
    // End of variables declaration//GEN-END:variables
}
